[package]
name = "vtubestudio-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "vts"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.47"
structopt = "0.3.25"
tokio = { version = "1.14.0", features = ["macros"] }
tracing = "0.1.29"
tracing-subscriber = "0.3.1"
vtubestudio = "0.2.1"
